spring:
  application:
    name: order-flow-system

management:
  endpoints:
    web:
      exposure:
        include: health,info

  info:
    env:
      enabled: true

info:
  app:
    name: Order Flow System
    version: 1.0.0
    description: Order management system
